name: new_comparator
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.11.14
  - esmf=8.9.0
  - esmpy=8.9.0
  - xesmf=0.9.2
  - xarray=2025.12.0
  - numpy=2.3.5
  - matplotlib=3.10.8
  - metpy=1.7.1
  - pyproj=3.7.2
  - pyyaml
  - pytest  
  - pandas  
  - cartopy 
  - herbie-data
