name: comparator
channels:
  - conda-forge
dependencies:
  - python=3.13
  - xesmf
  - pytest
  - rioxarray
  - cartopy
  - herbie-data
  - herbie
  - numpy
  - pandas
  - matplotlib
  - xarray
  - esmpy=8.9.0
  - esmf=8.9.0
