[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "comparator"
version = "0.0.0"
dependencies = []

[tool.setuptools.packages.find]
include = ["comparator"]
